### ISSUE TITLE
myApi 1.3 Bug

### ISSUE THREAD

**Issue by WiseKnow** [myApi/myApi#1]
My website is www.WiseKnow.Com Some articles the link "Add a comment" it show "");'>Add a comment" as the attached picture and when click the link it can't show Comment Lightbox as others. This error happen in all browsers : IE 9, Firefox 3.6, Google Chrome 10

**Comment by thomaswelton** [comment]
Fixes for the comments plugin, errors would occur when the article title had an apostrophe Closed by 05db558d3bdd59fff566f57c483e988a4c659aaf Thanks to @WiseKnow for finding this

**Comment by thomaswelton** [comment]
I think this should be fixed for you now. This fix is not currently released as part of a myApi version, the most recent version is 1.3.
But you can get this fix by downloading the "master" branch here
https://github.com/thomaswelton/myApi
Try it out and let me know if you have any other issues.

If you find myApi useful please review it here
http://extensions.joomla.org/extensions/social-web/facebook-display/11624

**Comment by WiseKnow** [comment]
Thanks for Fixing the Bug !!

I have just find other issue that when I use IE 9 at the "Connect with Facebook" button there are no Avatar shown in below and click "Add a comment" link it not show pop up Comment Lightbox as other browser. Maybe I config IE not correctly or not. Pls tell me how to solve this problem !!

**Comment by thomaswelton** [comment]
Hey, late last night I added a new fix for myApi. The defect #2 explains that avatars were not being properly imported. Is this the issue you are having?
Try getting the latest version, if this problem happens again could you please send me a screen shot
