### ISSUE TITLE
Warning... plugin operating in compatibility mode....

### ISSUE THREAD

**Issue by dvelco** [myApi/myApi#104]
I am getting this error on pages where a comment has not yet been made... I've also seen it on another website that uses the MyAPI plugin... please help and fix.  On pages where there has been comments made, this error does not appear.

Error:
Warning: this comments plugin is operating in compatibility mode, but has no posts yet. Consider specifying an explicit 'href' as suggested in the comments plugin documentation to take advantage of all plugin features.

Here's a link to one of my pages with this error present:  http://www.dennisvelco.com/gallery/awakening/heal

**Comment by djadamh** [comment]
I also have this issue

**Comment by aghoenk** [comment]
You can try this :

find this file :  ../plugins/content/myApiComment.php

find this line : 

```

$comment_box = '<fb:comments app_id="'.$facebook->getAppId().'" migrated="1" xid="'.$xid.'" url="'.$commentURL.'" numposts="'.$comments_numposts.'" width="'.$comments_width.'" colorscheme="'.$comments_scheme.'"></fb:comments>';

```

then alter  url="'.$commentURL.'" with  href="'.$commentURL.'"

the new line should be :

```

$comment_box = '<fb:comments app_id="'.$facebook->getAppId().'" migrated="1" xid="'.$xid.'" href="'.$commentURL.'" numposts="'.$comments_numposts.'" width="'.$comments_width.'" colorscheme="'.$comments_scheme.'"></fb:comments>';

```

Hope can solve the problem.

**Comment by dvelco** [comment]
To be 100% clear.. are you stating to find the "find this line" and REPLACE with the "the full line"?
Thanks.

**Comment by aghoenk** [comment]
yup.

**Comment by dvelco** [comment]
Hey.. I see you have put out a new version on Dec 13th.
I uninstalled my old version and trying to install your latest version..
After I add the FB API ID and Secret code... 

I get these errors..... 

Warning: array_merge() [function.array-merge]: Argument #1 is not an array in /home/mvelco/public_html/dennisvelco.com/plugins/system/myApiOpenGraph.php on line 50

Warning: implode() [function.implode]: Invalid arguments passed in /home/mvelco/public_html/dennisvelco.com/plugins/system/myApiOpenGraph.php on line 58

On FB User admin page in your backend admin area...
Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/mvelco/public_html/dennisvelco.com/libraries/joomla/database/database/mysql.php on line 344

When I choose the Real Time back end admin tab....

Warning: array_merge() [function.array-merge]: Argument #1 is not an array in /home/mvelco/public_html/dennisvelco.com/plugins/system/myApiOpenGraph.php on line 50

Warning: implode() [function.implode]: Invalid arguments passed in /home/mvelco/public_html/dennisvelco.com/plugins/system/myApiOpenGraph.php on line 58

Warning: file_get_contents() [function.file-get-contents]: URL file-access is disabled in the server configuration in/home/mvelco/public_html/dennisvelco.com/administrator/components/com_myapi/models/realtime.php on line 45

Warning: file_get_contents(https://graph.facebook.com/oauth/access_token?client_id=114265345277966&client_secret=7172d3504c75d71ee45c34f7f247a18c&grant_type=client_credentials) [function.file-get-contents]: failed to open stream: no suitable wrapper could be found in /home/mvelco/public_html/dennisvelco.com/administrator/components/com_myapi/models/realtime.php on line 45

Fatal error: Uncaught OAuthException: (#15) This method must be called with an app access_token. thrown in /home/mvelco/public_html/dennisvelco.com/plugins/system/base_facebook.php on line 1028

ANY THOUGHTS????

My other half is a web application developer if I need to get him involved.
I have to completely uninstall your application else it shows all these errors on my front end and bombs out my website.

Thanks.

Dennis Velco

**Comment by Lynartas6i** [comment]
The fix work just fine! 
The only problem is that you loose all comments,I really want to fix this issue and still have all the comments in place..
Has anyone found a solution to this issue?

Joomla 1.5.25
MyApi 1.3.4
