### ISSUE TITLE
Error Username and password do not match or you do not have an account yet. 

### ISSUE THREAD

**Issue by djadamh** [myApi/myApi#105]
I have this error

Error
Username and password do not match or you do not have an account yet.

This changes the whole layout of the template so it clumps all together... Also takes away the menus so you can't do anything.
Can't log on or off...
www.flaresuk.com

**Comment by hannov** [comment]
Hi,
I am getting the same error.
1. Installed vanilla Joomla 1.5.25
2. Install latest Myapi
3. added VB api code
4. change and save settings
5. Preview the web site and get the following error:  "Username and password do not match or you do not have an account yet."

I might be a noob here, but don't know what went wrong and how to fix it, please help.
www.groundworxjj.com/joomla

**Comment by labratz** [comment]
Hi,

Has anyone got a solution for this yet?  I am using the latest Myapi (v1.3.5) and getting the same errors while using Joomla 1.5

**Comment by Shedyk** [comment]
I get the same Error:  Username and password do not match or you do not have an account yet.

www.creativewriting.co.ke
