### ISSUE TITLE
Connect issues with new FB Api

### ISSUE THREAD

**Issue by mkrokos** [myApi/myApi#106]
Since yesterday, 14-12-2011, the "connect with facebook" function ceased to work. I guess it has something to do with the new FB Api or with OAuth. we get an "invalid token" error during the requests. 

Any ideas?

**Comment by shally87** [comment]
Same thing happen here..can help me with this?

**Comment by mkrokos** [comment]
Anyone?

**Comment by mkrokos** [comment]
Five days later and still no response from the developer... well, ignoring a problem won't make it disappear, correct?

**Comment by shally87** [comment]
There is a fix that i just know today too.Please search in their forum. He has release a new version..

**Comment by mkrokos** [comment]
Thanks shally87! I will check it out

**Comment by mkrokos** [comment]
Where do you find this new version, btw? And where is the forum?

**Comment by shally87** [comment]
Check it herehttp://www.myapi.co.uk/index.php?option=com_kunena&Itemid=56&func=view&catid=16&id=1264

Regards,
Shally Martin

Visit My site at www.TechInfo.Com.Myandwww.HotOnBlog.Com.
