### ISSUE TITLE
myApi 1.3.5.0 crash site after installation

### ISSUE THREAD

**Issue by XiaofengGH** [myApi/myApi#110]
I assume myApi is compatible with joomla 1.7 as its stated in joomla extensions directory,

Here is Issue :
After installing clean joomla 1.7.3 and then installing myApi 1.3.5.0 joomla site completly stop responding.
Browser does not return anything - just blank white page.
It returns nothing (white page) for any url related to this joomla installation (home page or administrator page or any other)

To reproduce this issue for debugging you may :
1. Install xampp 1.7.7
2. Install fresh joomla 1.7.3 on previously installed xampp 1.7.7
3. install myApi 1.3.5.0
4. From now on - previously working joomla no more responding. (completly crashed)

Additional information :
Xampp 1.7.7 provides following serwer environment :
- Apache 2.2.21
- PHP 5.3.8
- MySQL 5.5.16

Note :
I have posted this information on your demo site but it was quickly moderated (deleted) by you.
I understand that you may see it as anty advertisement (and because of this, info was deleted)
I want you to know that it was not my intention to make you any anty advertisement,
i wanted to help and let you know there are some problems with your extension.
However please consider that your extension is currently downloaded by many people everyday
and probably most of them will completly destroy his sites, which may soon bring you alot of bad posts
from angry users in joomla extension directory, your demo site and support forums.
Please try to fix this issue as soon as possible to avoid this.

**Comment by XiaofengGH** [comment]
Or at least, if you cannot make it joomla 1.7 compatible,
please remove from joomla extensions directory icon which say that this extension is joomla 1.7 compatible,
which with addition to many good comments, misslead great number of joomla 1.7 users and make them destroy his sites.

**Comment by ranioli** [comment]
try disabling modules and plugins one by one and see whether that fixes it... i had my j1.5 site lose all its css.. this fixed it.. luckily the ones i need worked fine.. had some extra ones enabled which i disabled
