### ISSUE TITLE
New User Registration with Joomla Not Successful

### ISSUE THREAD

**Issue by ayfaizal** [myApi/myApi#14]
Hi,

i have install latest pack myApi 1.3.1-10, and configured successfully with Facebook AppID and app secret, now im trying to connect with facebook from frontpage, i did 'facebook Like' and it says 'connecting', then its redirected to Home page and it displays following Error

"Please enter your name:"

so far facebook user not registered with my joomla page. pls assist me further.

Thanks.

**Comment by thomaswelton** [comment]
Could you try installing the latest test code from here https://github.com/thomaswelton/myApi/zipball/master and see if it resolves your issues.

**Comment by ayfaizal** [comment]
i did reinstalled with latest code 1.3.2.0

but Same problem and getting same error message "Please enter your name:"

**Comment by thomaswelton** [comment]
Can you please post a link you your site

**Comment by thomaswelton** [comment]
And try version 1.3.3

**Comment by ayfaizal** [comment]
i did try with 1.3.3, also same problem, please find my link here http://portal.telbru.com.bn/letstrek/video

Thanks.
