### ISSUE TITLE
Login module mysql_num_rows()

### ISSUE THREAD

**Issue by auchi** [myApi/myApi#16]
Joomla: Versión 1.5.20
MyApi: 1.3.1

Whe i try to connect via the button on the module it stays "Connecting" and via firebug i got this error

<b>Warning</b>:  mysql_num_rows(): supplied argument is not a valid MySQL result resource in <b>MY_SITE/libraries/joomla/database/database/mysql.php</b> on line <b>344</b><br />

["myApiModal.open('Facebook Connect','Hi, login or register below. You can create a new user accout, or link your facebook account to an exisiting user.', AND CONTINUES...

Any tip?

**Comment by thomaswelton** [comment]
Not able to replicate this. Is it causing any problems? If it is, and it's possible to turn off error messages then that may be best

**Comment by thomaswelton** [comment]
Version 1.3.2 is available, try it out.

**Comment by auchi** [comment]
Thanks! I will try it!

**Comment by thomaswelton** [comment]
Did it work? If not can you post the error message again and I will fix it. Otherwise you can close this defect, thanks.

**Comment by thomaswelton** [comment]
Ok, please reopen if the error persists.
