### ISSUE TITLE
Parameters Global Configuration is blank

### ISSUE THREAD

**Issue by xacommerce** [myApi/myApi#17]
When I upgraded to 1.3.1 from 1.0 my comments and like buttons stopped working.  When I went in to edit the parameters under global configuration to edit the facebook API key and code, it is completely blank. It won't allow me to input the necessary info from facebook.

**Comment by thomaswelton** [comment]
Try editing the plugin directly, there is a system plugin called myapi connect that holds this information

**Comment by thomaswelton** [comment]
Ok the new version has no Parameters that opens a blank box. Instead the app settings are added to the main menu.
