### ISSUE TITLE
UTF-8 titles shared unreadable charachter under fb

### ISSUE THREAD

**Issue by abed** [myApi/myApi#18]
when you comment on non english article it share the link on facebook with unreadable title 

to test it  go to http://www.kermalek.com

thank you

**Comment by thomaswelton** [comment]
You are currently using myApi version 1.3.1. In this version myApi was not fully up to date with all of the new Facebook parameters. But now it is, and many of the parameters in the comments box have been removed. Looking at your site's source I can see the messed up characters in the title parameter of the comments box, this parameter is no longer required by Facebook.
I am hoping that once you have the new code Facebook will scrape the page for the article information and it may display correctly. If you'd like you can download the latest "master" branch of myApi and try it out, but do not test this code on your main site as it may have untested defects.

**Comment by thomaswelton** [comment]
Can you install the new code https://github.com/thomaswelton/myApi/zipball/master and let me know how it goes.

**Comment by thomaswelton** [comment]
@abed see if version 1.3.3 works for you.

**Comment by thomaswelton** [comment]
Have you tried the newest version? I haven't had anyone else mention this issue
