### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by abed** [myApi/myApi#19]
when you change the text for login with facebook in module it didn't affect the site 

we are ready as Ttawor.com  to contribute with you in arabic translation for your component 
and also we are ready to be part of myapi team 
add me to skype : abed.fatafta

Thanks

**Comment by thomaswelton** [comment]
Hey, thanks for the offers.
I'll be setting up language files soon.

**Comment by thomaswelton** [comment]
Yes I can confirm that the string "Connect with Facebook" was hardcoded into the module. This has been updated and will now show the value in the parameters. This new code is in the master branch and will be packed into a version shortly.
