### ISSUE TITLE
myApi + Joomgallery + sh404sef: broken image urls.

### ISSUE THREAD

**Issue by lexthoonen** [myApi/myApi#23]
I enabled sh404sef on my site today, especially for having nice urls for my photo gallery 

(joomgallery). The urls look fine, but (only) the detailed images show broken links. The images 

can't be found. I started looking at the forums of joomgallery and they all pointed to myApi. 

I've checked the forums here too and here as well a few people have been posting questions, 

however, with no solutions.

if I disable the plugin: system - myApiConnect, at the front end, I get blank pages. Disabling 

other myApi plugins did not seem to have an effect on the disappearing images.

The (not working) image url with everything enabled is:
/photos/nature/animals/img-greattit-007-7184

where it should be:
/components/com_joomgallery/img_pictures/nature_3/animals_269/great_tit-007_20110420_1155590021.jpg

The problem is not happening with the thumbnails for example.

I'll put an url here, but I'll have to disable something to make sure people get to see the images again, probably sh404sef.

http://www.gran-canaria-info.com/photos/nature/animals

However, it woudl be great if it all could work together. 

What exactly in myApi could cause that image url to break?

p.s. I've got the latest version of myApi (1.3) (just downloaded it now and upgraded), sh404sef2_2.2.5.964 and latest version of joomgallery too.

Thanks,

Lex

**Comment by thomaswelton** [comment]
I found this article http://www.en.joomgallery.net/faq/general-faq/problem-with-certain-system-plugins.html
try this, in the myApiModal plugin. /plugins/system/myApiModal.php change line 48 from

function onAfterInitialise(){

to this

function onAfterRender(){

let me know if that has any effect.

**Comment by thomaswelton** [comment]
Also you say "Disabling other myApi plugins did not seem to have an effect on the disappearing images." Dos this mean that if myAPi is completely uninstalled it still does not work? Is there a scenario where this will work on your site with or with myAPI?

**Comment by thomaswelton** [comment]
Ok so version 1.3.3 fixes a defect that I had in the router.php file which may have caused problems. If this has not helped then I'll have to get all this setup an replicate it on my local.
