### ISSUE TITLE
Language files not installed properly - Master branch

### ISSUE THREAD

**Issue by kparzinger** [myApi/myApi#24]
Hi All,

hm... seems something going wrong. I installed the 1.3.1-62 but it seems that all variables not set for example i see in every section of control panel entries like that:

PARAM_ARTICLE_LABEL     PARAM_VIEW_BOX PARAM_VIEW_LINK PARAM_VIEW_NONE
PARAM_LIST_LABEL    PARAM_VIEW_BOX PARAM_VIEW_LINK PARAM_VIEW_NONE
PARAM_BLOG_LABEL    PARAM_VIEW_BOX PARAM_VIEW_LINK PARAM_VIEW_NONE
PARAM_SHOW_LABEL    PARAM_SHOW_ALL PARAM_SHOW_SELECT

and not the names of variables. On my root there are 2 websites, one wiht 1.3.1 and one with hte new 1.3.1.62 and the old one is running so in my opinion its a failure on the new one.

see: http://parzinger.info/ << 1.3.1-62
see: http://gruenweg.de/ << 1.3.1

Thanks.

**Comment by thomaswelton** [comment]
Yeah so something is not quite right here :)
It works ok for me, I think maybe the new files are only copied on a clean install. 
For now you could fix this manually by getting the language files out of the installer and placing them in your /languages and /administrator/languages folders.
