### ISSUE TITLE
Comments Lightbox Expands Past the Visible Area On Screen

### ISSUE THREAD

**Issue by kartzke** [myApi/myApi#25]
If the comments Lightbox is enabled and there are many comments in the thread, the lightbox will expand past the visible area on the screen.  This presents two main issues:
1. There are no scroll bars in the lightbox, so users cannot read comments that are below the fold.
2. Users cannot close the lightbox because the close button is below the fold. 

I've verified this problem exists on my test site, as well as myapi.co.uk, and it is present in all browsers.

A max height should be defined for the lightbox so it fills up a majority of the visible area on the screen, but does not go below the fold.  We'll also need to enable scroll bars so users can read through the comments thread in the Lightbox.

**Comment by kartzke** [comment]
I also noticed that the z-index of the lightbox shows up as 2 on my test site.  The top menu has a higher z-index, so it appears on top of the lightbox.

**Comment by thomaswelton** [comment]
also looks like there is an issue with IE 7

**Comment by thomaswelton** [comment]
Made an error when I checked in 85d0836b28b1a15aee311f1c2afcf7b2d25dd34a this should have been closed with that commit last night
