### ISSUE TITLE
Open Graph Meta Data Issues & Concerns

### ISSUE THREAD

**Issue by kartzke** [myApi/myApi#26]
I've noticed a couple bugs with the Open Graph Meta Data on my test site, so I wanted to submit this as feedback.  I've also included a few ideas for improvements to the system:
1. The OG:URL works great on the homepage, sections and categories. But on article pages, I noticed that it uses the non-SEF URL.  Also, the question mark gets stripped after "index.php", so the article URL is broken.
2. I could not find a way to add a value to the fb:admin property.  A text box should be included in the Open Graph admin area so users can enter one or more admin ID's.
3. fb:page_id should also be included as an optional property.  Essentially, this is another way to claim a domain on Facebook, similar to FB:app_id and FB:admin.  I think this should be included because there may be a scenario where a webmaster wants to grant all page admins access to insights and moderation rights.  This would be much easier than maintaining an active list of Facebook ID's or application admins. 
4. The standard values for og:type are pretty good, but there might be some sites out there that need to customize this value.  It would be good to build in an override system so webmasters can choose the correct value for their site. 
5. og:site_name should be customizable. Some people will want to use a Brand name or the domain name.  It currently uses the Meta Title of the homepage. 

6: og:image - Specifying a default image is great, but for articles, myApi should try to scrape the first image found in the post and use that URL.  If no image is found, then it uses the default image.  This would help many types of content go viral.  An even better solution would be if myApi could scrape and use all images found in the post and insert the values into OG:image,  separated by commas.  That way, users could pick which image they wanted to share.

**Comment by thomaswelton** [comment]
Ok so all fb admins are added automatically. If you are a super admin and linked you account to your site then your FB id will be added as a FB page admin (this is cached so you may need to clear joomla cache)

og:image IS found by looking in the article for the first image, not just should. It uses an HTML parser and saved the data in the module attributes to avoid doing a regexp on every page load, if it's not working for you its a defect.

More customizable parameters will be coming.

Just to confirm the only defect here is defect 1 right? I will take a look at that

**Comment by thomaswelton** [comment]
And it's not setting site name form the meta tags, the site name is the same as the site name in the Joomla global config. This value makes both meta tags, so you could change it there.

**Comment by thomaswelton** [comment]
:) So I believe points 1,2,3 have been fixed in the new code. Point 6 should be ok as this was already feature (but may have a bug) and point 4 and 5 will be added as parameters in the future. Thanks for the help in finding these issues.

**Comment by kartzke** [comment]
Nice, good work Thomas!  I just installed the latest Master branch on another one of my test sites. The og:image worked on this site, so I'm not sure what was happening on my other site, I'll check it out tomorrow.  The OG:URL on the article pages appears to be working correctly now too.  And I saw that 2 and 3 now have input boxes in the admin area, which is great.

I do have a weird issue with FB Comments on this new test site.  For some reason, it's ignoring the color scheme selection and the colors are all screwy.  I checked in both Chrome and Firefox, and manually deleted the cache files.  Firebug shows correct CSS values on the front end, so I'm not sure what's going on there.  I'll spend some time on this tomorrow and see if I can figure it out.

Anyway, thanks for looking into these meta tag issues.  I'll upload the latest Master to my test site at work tomorrow and report back if I find any other issues.

**Comment by thomaswelton** [comment]
Awesome. Regarding the dark or light comment boxes I do know at one point there was a Facebook bug with that. I think there was a bug where the dark scheme did not work if you were the admin for the app. So keep an eye on this and we'll open a new issue for it.
