### ISSUE TITLE
Fatal error: Cannot access protected property JInstaller::$_overwrite in [domain and so on]/administrator/components/com_myapi/install.myapi.php on line 46

### ISSUE THREAD

**Issue by bendykowski** [myApi/myApi#28]
I'm new in Joomla society and it's one of the first installs for me (Joomla extension) so don't bite if it's some stupid problem.

When I'm trying to install it (1.3.2.1 version) I get this error all the time, whatever I'm trying to do:
"Fatal error: Cannot access protected property JInstaller::$_overwrite in [domain and so on]/administrator/components/com_myapi/install.myapi.php on line 46"

What to do with it?

**Comment by thomaswelton** [comment]
What joomla version you running. myApi only works with joomla 1.5

**Comment by bendykowski** [comment]
Oh, I see. I'm using Joomla 1.6.3. Are you planning to rewrite myApi to work with the newest version of Joomla?

**Comment by thomaswelton** [comment]
At some point soon.

**Comment by bendykowski** [comment]
Thanks for quick answer and I keep crossing fingers for myApi.
