### ISSUE TITLE
A few problems on my site. 

### ISSUE THREAD

**Issue by patience-zz** [myApi/myApi#29]
--When you are not logged in on facebook, the comment count shows up as "0" but when you click on the "addcomment" link ..    you will see comments. works fine when you are logged in. 

-- When someone replies to your comment.. on their facebook page it says" commented on {creator}'s post "

 --I can't seem to figure out how to add "add comment" link to the frontpage and when someone click on the article then show  the "comment box" I tried all combinations. It's either a lightbox or a box comment on your front page. 

--I am using K2 for my articles and When you press send i get this error  "The page at http://xxxx.com/index.php?option=com_content&amp;view=article&amp;id&amp;Itemid=51 could not be reached." 

--I can't see people's comments unless I am logged in as an administrator. < comment setting is for public

--When someone "Like" something and posts the link on their facebook.. clicking on that link will take them to my website asking for permission to login but the article is set to public.

**Comment by thomaswelton** [comment]
I haven't used K2 but I think it handles articles and does it's own thing. I think it may need some new integration to work. As for the other issues they can be addressed.

**Comment by thomaswelton** [comment]
created #31 and #32 to deal with two of the separate defects you mentioned with the comments

**Comment by patience-zz** [comment]
you are right about K2. if you integrate it with K2, your reviews will double because almost all Joomla sites use K2 for their blogs. Most of the new extensions support K2 as-well. 

Don't have time today to do some more testing.. got lots of homework.  I will download the 1.3 when i get a chance and let you know about any problems I face.

**Comment by thomaswelton** [comment]
Ok, instead of downloading 1.3.3 try the master branch, it contains newer code. Since I read your last post I started work on K2 integration, I got V1 working on my website so check it out. 
master zip - https://github.com/thomaswelton/myApi/zipball/master

**Comment by thomaswelton** [comment]
How is 1.3.4 working for you? Just wonder how much of the above hasn't been looked into as I know some of the item mentioned have been talked about separately.
