### ISSUE TITLE
Locale settings ....

### ISSUE THREAD

**Issue by VenimK** [myApi/myApi#3]
edited myApiConnect.xml en myApiConnect.php.
but on site i can 't find, where to adjust the local settings >???

**Comment by thomaswelton** [comment]
You do not need to edit any files. You only need to edit the plugin parameters from the Admin backend.

**Comment by VenimK** [comment]
I Have no such option ?
https://skitch.com/venimk/r2s49/its-latin-time-administratie

**Comment by thomaswelton** [comment]
Hmm ok, which version are you installing. github allows to host multiple versions of a file. Version 1.3.1 does not have this feature. It is a feature in the "master" branch and will be officially packaged into a version after more testing.
To use the new version download the latest version https://github.com/thomaswelton/myApi
