### ISSUE TITLE
commented on {creator}'s post

### ISSUE THREAD

**Issue by thomaswelton** [myApi/myApi#31]
When leaving a comment the post to Facebook appears with the text commented on {creator}'s post

**Comment by patience-zz** [comment]
Tested it with the master build and still the same. Can't see other peoples comments when I am logged in as an admin. 

and the creator post still exists.

**Comment by thomaswelton** [comment]
What is your URL?

**Comment by thomaswelton** [comment]
Found an existing bug in the Facebook bug tracker, posting link http://bugs.developers.facebook.net/show_bug.cgi?id=17963

**Comment by thomaswelton** [comment]
Facebook say they fixed this in the beta tier 
http://bugs.developers.facebook.net/show_bug.cgi?id=17963

**Comment by thomaswelton** [comment]
Can you confirm a fix for this?

**Comment by patience-zz** [comment]
I think it's fixed, when someone comments, it says "commented on facebook.com" 

Having issues with the comment counter, it shows up maybe once every ten times that you refresh the page. The like box messes up as well, it shows pictures of 1 person in 3 places.

**Comment by thomaswelton** [comment]
I think there is an existing defect for the comment count, so I'll be working on that. But I'm gonna close this defect, but feel free to make a new one for any other issues
