### ISSUE TITLE
Comment count incorrect when logged out

### ISSUE THREAD

**Issue by thomaswelton** [myApi/myApi#32]
When you are not logged in on facebook, the comment count shows up as "0" but when you click on the "addcomment" link .. you will see comments. works fine when you are logged in.

**Comment by patience-zz** [comment]
The problem still exists in Firefox and IE 8

**Comment by thomaswelton** [comment]
Yep, once it's fixed you'll get a notification that it is closed.

**Comment by IMspintheweb** [comment]
Any word on this Thomas?
