### ISSUE TITLE
Jumi conflicts

### ISSUE THREAD

**Issue by SimonaV** [myApi/myApi#33]
Some serious problem

It 'an excellent product, but creates a problem for me:

1) when I install MyApi, and I try to share on facebook my website articles, instead of displaying the title of the article shows the name of my website. To return to a normal situation I must disable plugins "Content - myApiOpenGraphContent" and "System - myApiOpenGraph", and this greatly restricts MyApi.

2) MyApi conflicts with the Jumi plugin, used to insert at the end of the article, "Share" button with a simple string { jumi [jumi_includes /share.html ]}. When the Jumi button is shown the comment box not appear.

3) Even if you do not insert Jumi string, when there are many facebook comments, only one appears, despite the correct settings.

Sorry for bad english.

**Comment by thomaswelton** [comment]
please provide a url for your site.
