### ISSUE TITLE
"Please enter your name:"

### ISSUE THREAD

**Issue by erecpr** [myApi/myApi#35]
hi, i have the "Please enter your name:" when login in, and the share button doesn't do anything, it just open a Facebook dialog and keeps loading.

im using 1.3.3-8 version, joomla 1.5 with jcomments, hwdvideoshare installed
my site is: lafiebre.ws/site

thanks

**Comment by thomaswelton** [comment]
What is you site url and base domain set as IN your FB app settings?
also can you add me on FB to live chat http://www.facebook.com/kingwalton

The issue with the border is a quick fix, a bug introduced yesterday with the new layout

**Comment by erecpr** [comment]
domain in FB app is "lafiebre.ws" site url is http://lafiebre.ws/site (cause im testing in the "site" directory)

**Comment by erecpr** [comment]
i added you in FB, also, i noted that in the FB app i put domain as "lafiebre.ws" it would change itself to "lafiebre.ws/site"

**Comment by thomaswelton** [comment]
Removed reference to defects with CSS and borders and created new defect #36
