### ISSUE TITLE
Share button not working

### ISSUE THREAD

**Issue by jfalcone** [myApi/myApi#36]
Installed 1.3.3 on Joomla 1.5.latest on Linux at www dot armecal dot com.  Joomla works fine and all the other myApi features seem to work.  Tested on XP, Win7 and Mac with Firefox 4 and IE 8 with 2 different facebook users.   I've taken some screenshots with IE8 and the odd thing is that when the page first comes up there are spinners on each article (see the first screenshot).  Then when I hit a share button, the facebook popup comes up with another spinner and they all spin together forever.     With Firefox 4, the page loads fine (without spinners) but the share button just causes the facebook popup to come with another spinner.

screenshots:
http://imageshack.us/photo/my-images/844/fbmyapi1.jpg
http://imageshack.us/photo/my-images/3/fbmyapi2.jpg

**Comment by thomaswelton** [comment]
weblink?

**Comment by jfalcone** [comment]
www.armecal.com/the-news - same as before.

----- Original Message ----- 
From: "thomaswelton" 
reply@reply.github.com
To: jrf@acm.org
Sent: Wednesday, June 01, 2011 10:39 PM
Subject: Re: [myApi] Share button not working (#36)

**Comment by thomaswelton** [comment]
sorry it's hard to keep track of everyones urls

**Comment by thomaswelton** [comment]
For me the share button works ok but a few people have mentioned problems with it today so it may be a temporary Facebook problem.
However you should install the latest code found here https://github.com/thomaswelton/myApi/zipball/master just install it over your current version. I has much better positioning of the comments and buttons which will solve some layout issues you are having, plus it may also fix issues with your share button.

**Comment by jfalcone** [comment]
Thanks for the update but it still doesn't work but with some twists.  

With this install I got Firefox download popups for recommendations.php 
(calendar page) and like.php (the-news page) when I first went to the website.
Then when the-news page loaded, check out the button positioning in the 
screenshot - layout issues have gotten worse. 

 And I got the spinner popup from Facebook when I hit the share button.
On Firefox 4 on Win7 using my own Facebook account.

---

From: thomaswelton 
reply@reply.github.com
To: jrf@acm.org
Sent: Thu, June 2, 2011 2:06:19 AM
Subject: Re: [myApi] Share button not working (#36)

For me the share button works ok but a few people have mentioned problems with 
it today so it may be a temporary Facebook problem.
However you should install the latest code found here 
https://github.com/thomaswelton/myApi/zipball/master just install it over your 
current version. I has much better positioning of the comments and buttons which 
will solve some layout issues you are having, plus it may also fix issues with 
your share button.

## 

Reply to this email directly or view it on GitHub:
https://github.com/thomaswelton/myApi/issues/36#comment_1279750

**Comment by thomaswelton** [comment]
On your site you have the comments box, and a add a comment link. You also have 2 like buttons per article. Can you try to uninstall everything, plugins modules first then component and reinstall. If looks like you have 2 versions running?

But anyway the share button worked for me.

**Comment by thomaswelton** [comment]
Actually on close look there is a div called jfbcomments so looks like you have that running as well as myApi.
jfbconnect does a lot of the stuff myApi does so you don't need both.

**Comment by jfalcone** [comment]
I thought I had disabled JFBC completely but I've gone and disabled the rest of 
it so there are no double boxes showing.
Sorry I had run tests with JFBC earlier and not disabled every little piece.

Layout is still bad for the myAPI buttons and the share button still doesn't 
work.

The big question is why does the Share button work for you, but not for me or my 
wife?
Other functions seem to work - just did a Like.

Do you still want me to uninstall/reinstall?

---

From: thomaswelton 
reply@reply.github.com
To: jrf@acm.org
Sent: Thu, June 2, 2011 10:55:54 AM
Subject: Re: [myApi] Share button not working (#36)

Actually on close look there is a div called jfbcomments so looks like you have 
that running as well as myApi.
jfbconnect does a lot of the stuff myApi does so you don't need both.

## 

Reply to this email directly or view it on GitHub:
https://github.com/thomaswelton/myApi/issues/36#comment_1282233

**Comment by jfalcone** [comment]
Just tested on Safari on Mac - layout is perfect! (see screenshot) but Share 
button still doesn't work.

Cleared cache on Firefox - made no difference in layout.  And there are no JFBC 
directives in the source anywhere now.

---

From: thomaswelton 
reply@reply.github.com
To: jrf@acm.org
Sent: Thu, June 2, 2011 10:55:54 AM
Subject: Re: [myApi] Share button not working (#36)

Actually on close look there is a div called jfbcomments so looks like you have 
that running as well as myApi.
jfbconnect does a lot of the stuff myApi does so you don't need both.

## 

Reply to this email directly or view it on GitHub:
https://github.com/thomaswelton/myApi/issues/36#comment_1282233

**Comment by thomaswelton** [comment]
Yeah you may as well try the uninstall reinstall.
Also lots of people have reported problems with share buttons only for them to fix themselves later. Try clearing you browser cache and stuff too that may help.

**Comment by jfalcone** [comment]
OK, just for kicks, I tried using the Share button on your home page at 
myapi.co.uk and it didn't work.  Same problem with spinner in popup never 
finishing.
So perhaps it is something in my profile?  I don't know.  
I don't see why since I've voluntarily connected to your site and I'm 
voluntarily clicking 'share' - weird!
If that isn't opt-in, I don't know what is...

---

From: thomaswelton 
reply@reply.github.com
To: jrf@acm.org
Sent: Thu, June 2, 2011 11:21:27 AM
Subject: Re: [myApi] Share button not working (#36)

Yeah you may as well try the uninstall reinstall.
Also lots of people have reported problems with share buttons only for them to 
fix themselves later. Try clearing you browser cache and stuff too that may 
help.

## 

Reply to this email directly or view it on GitHub:
https://github.com/thomaswelton/myApi/issues/36#comment_1282478

**Comment by sailorz** [comment]
Still happening to me also. I thought it was the browser cache originally, but clearing the cache doesn't appear to resolve this for me now. Firefox and Chrome on Linux.  IE8 on Windows 7.

**Comment by jfalcone** [comment]
Still happening with 1.3.4 - I'm going to completely remove and re-install and see what happens.

**Comment by thomaswelton** [comment]
Ok let me know how it goes, unfortunately for me this still work when I visit your site. If I could replicated the problem maybe I could fix it. Apologies.

**Comment by ArroganceEmu** [comment]
I'm having the same problem

**Comment by ArroganceEmu** [comment]
I've tried this (see the link) and I think thats may be the problem. The tags og:xx are shown in the page but facebook is not recognizing them.

http://developers.facebook.com/tools/lint/?url=http%3A%2F%2Fwww.diariodeunidiota.com%2Findex.php%3Foption%3Dcom_content%26view%3Dcategory%26layout%3Dblog%26id%3D7%26Itemid%3D5

The tags are shown like this:

meta property="fb:app_id" content="intentionally omited" />
meta property="og:title" content="Diario De Un Idiota" />
meta property="og:type" content="website" />
meta property="og:url" content="http://www.diariodeunidiota.com" />
meta property="og:image" content="http://www.diariodeunidiota.com/images/diariodeunidiota_50x50.png" />
meta property="og:site_name" content="Diario De Un Idiota" />"

first simbol < intentionally omited by me.

**Comment by thomaswelton** [comment]
That's interesting, looking at the source for your site I can see those meta tags have been set.

**Comment by ArroganceEmu** [comment]
Yes the tags have been set but facebook don't read them and I don't kwon what to do at this point.

**Comment by thomaswelton** [comment]
Could be a FB defect, the platform went offline yesterday for around an hour due to a spike in API response time, and today the latency is 3 times that which it is normally, so there could be issue with not expiring old cached data. But the URL linter is supposed to expire the cached data.
I'm not too sure right now, maybe it could be submitted to the Facebook bug tracker.

**Comment by fabinus** [comment]
Hello,
I'm the same problem... Share  button doesn't works correctly.
I have find a method where this button works:
I open a browser. I click the Share button (authentication facebook is not yet done). The popup authentication facebook opens. I enter my login and password, and the item I want to share appears and I can share it properly.

But classic share does not works:
If I am already authenticated on facebook (in the same browser session), I click the Share button, the popup opens but nothing happens (this charge indefinitely)

Important: I have the same behavior on your site http://www.myapi.co.uk/

My URL: http://urmattbc.net/jooml

I can test others things  if you want more information

Thank you for all

**Comment by fabinus** [comment]
Up, I'm alone to have this problem ? I don't think ..thank you :)

**Comment by fabinus** [comment]
Up, no anwer about that please ?
thank you

**Comment by mmafightgr** [comment]
same problem with fabinus. Help please
