### ISSUE TITLE
Fatal Error: Allowed Memory Size Exhausted in myApiDom.php

### ISSUE THREAD

**Issue by smalls212** [myApi/myApi#42]
I recently updated myApi, and everything has been working perfectly with one exception.

When I try to access the Article Manager in the admin panel, i receive the following message: 

"Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 24 bytes) in /public_html/plugins/system/myApiDom.php on line 878"

I can access the Category and Section Managers fine, but not the Article Manager.

Thanks for the help!

**Comment by thomaswelton** [comment]
Apologies, can you add me on FB http://www.facebook.com/kingwalton we'll live chat about it

**Comment by smalls212** [comment]
Thanks for the help! 

For others reference, I just had to install this file (as I had upgraded from a previous version): https://github.com/thomaswelton/myApi/zipball/master
