### ISSUE TITLE
hide share, like and send button in blog view

### ISSUE THREAD

**Issue by shafiun** [myApi/myApi#46]
is it possible to hide share, like and send button in blog view ??
We  want them only in article details view, not in blog or list view
there is option for comment, but not for share, like/recommend, send button
it'd be great if we user get this from myApi :)

**Comment by thomaswelton** [comment]
Compared to adding some of the other more complex new features adding this was a joy :) 
Simple changes to the code, and big improvements to usability.

**Comment by thomaswelton** [comment]
You can leave a review for myApi here http://extensions.joomla.org/extensions/social-web/facebook-display/11624

**Comment by shafiun** [comment]
thanks a lottttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt :)

**Comment by thomaswelton** [comment]
:) no worries, you may wanna upgrade again soon I'm working on #34 which will allow a new view parameter for the comments
