### ISSUE TITLE
Fatal error on plugins/system/myApiTabs.php on line 49

### ISSUE THREAD

**Issue by etkritikonspoudon** [myApi/myApi#47]
Hello and thank you very much for this actively developed extension...

I am having a bit of a trouble:

As soon as I installed the most recent version of myapi 1.3.3-37, I got the following error and was unable to access my website from the front-end:
- Fatal error: Call to a member function getSignedRequest() on a non-object in /home/mysite/public_html/plugins/system/myApiTabs.php on line 49

I also had an concerning the language not showing in the back end, only the languages keys, with version 1.3.3...with the most recent version mentioned above I didn't even get to check if it also was the case...I uninstalled immediately because of the above fatal error

It would be nice if the plugins/modules could be installed independently for people looking just for facebook login/registration functionality

Best Regards

**Comment by thomaswelton** [comment]
If you can still access the backend disable this plugin, it's not required from the web front end. If you can't access the back end disable the plugin from the jos_plugins database.

I will correct the code so it doesn't die if it's not setup properly. Thanks for posting.

**Comment by thomaswelton** [comment]
Please friend me on Facebook http://www.facebook.com/kingwalton we'll live chat and I'll send you some new files to try.

**Comment by thomaswelton** [comment]
Apologies, yesterday I made changes that threw error messages if myApi was not setup properly. But these error messages were not being handled by some of the plugins. Install this zip https://github.com/thomaswelton/myApi/zipball/master

And then refresh your home page, you'll probably see an error myApi need an application ID, this can be setup from the myApi component admin view.

**Comment by etkritikonspoudon** [comment]
Thank you Thomas, I will install newest package and report back
