### ISSUE TITLE
Can I uninstall plugins/modules I don't use?

### ISSUE THREAD

**Issue by etkritikonspoudon** [myApi/myApi#49]
First of all I apologize if this is the wrong place to ask such a question...

But I have just setup your extension (works ok now) but there are too many plugins/modules I don't want to use...
I have disabled them, but I would also like to know whether  I can also uninstall them without harming the functionality of myapi...

As a feature request, could the extension be made to offer the option of not installing all plugins?

Thanks

**Comment by thomaswelton** [comment]
It fine to disable anything you don't use. Uninstalling provides not benefit ver disabling  but required extra time and will need to be uninstalled after every upgrade.
Unless you are desperate for a few mbs of disk space I'd just leave them disabled.

Please post all other questions or general discussions in the forum.
This is our bug trackers.

**Comment by etkritikonspoudon** [comment]
I would like to be able to post to your website's forum, however I am not able to...

I have logged in with facebook, but I am unable to login to the forum...
I have asked for my credentials to be sent to my email, they have, but I am still unable to connect to the forum when using them.

Here is the question I wanted to ask in your forum, I apologize for posting it here.
- How can I setup multi-step registration?

I don't like the way one-click registration works (in general, not in your extension)...I want the user to be able to set his desired username and his password.
With One-Click-Registration the user can only login with Facebook again, he doesn't have a password he knows of -he can set it in the "User Details" in Joomla afterwards, but he should be able to choose one when registering. Inability to set one's username could also be a problem...

As I see it, this Facebook registration/login functionality is a good way to make registration and participation in one's site easier, but the users may not want to appear with their Facebook name, assuming that they have used their real name to register to Facebook or they may want to login to the site without using the Facebook connect function, after registering...

Is there a way to do that?
