### ISSUE TITLE
6 June Master Build- Content Share Button Doesn't Retain Existing Count On Install

### ISSUE THREAD

**Issue by sailorz** [myApi/myApi#50]
6 June master Build '1.3.3-51-gc3523da'

The content share button is not retaining the existing count of shares.

Site www.baysidemustangs.com

**Comment by thomaswelton** [comment]
Hmm, I look at the difference in code between the two version and there was not too much that changed in link generation.
However, I did change the default parameter for the share button, now by default it will show a button, not a button_count.

Check the plugin parameter to make sure the button type it button_share

**Comment by sailorz** [comment]
That was it.

**Comment by thomaswelton** [comment]
Great, you had me worried for a second. Sorry about that.
