### ISSUE TITLE
Trouble installing new version in new Joomla installation

### ISSUE THREAD

**Issue by mkrokos** [myApi/myApi#52]
I am getting this message:

```
    JInstaller::install: File '/home/********/public_html/demo/tmp/install_4def3c6e5177a/tmpl/default.php' does not exist.

    Install Module Error
```

Joomla version: 1.5.23

**Comment by thomaswelton** [comment]
Hmmmm, can you try cleaning you cache and tmp dir. Also try unzipping the files, putting them on your site via FTP then doing an install from directory.
Add me on FB if you want to live chat http://www.facebook.com/kingwalton
If you want me to to best help you out set up an admin account ready for me

**Comment by mkrokos** [comment]
I managed to install by FTPing everything to a directory and install from there.

Thanks for the help!
