### ISSUE TITLE
Subdirectory Install - Misdirect after registration.

### ISSUE THREAD

**Issue by abed-fatafta** [myApi/myApi#6]
there is aproblem in myApi if joomla installed in subdirectory , 

the problem like that 
my joomla based in www.edalily.com/a/ and after connect it redirect me to
www.edalily.com/a/a/ which wired

**Comment by thomaswelton** [comment]
Thanks for reporting this, I had planned to look at this over the weekend but didn't have the time. I'll get this fixed asap

**Comment by abed-fatafta** [comment]
any new Updates man

**Comment by thomaswelton** [comment]
Apologies for taking so long to find and fix this. However it should now be ok. I setup in a subdirectory, replicated you issue, and then made a change which fixed it.
Have a look at the changes I made, you can use this to make edits to your site to fix the issue until I make a new release package. You could download the master branch but it's not advised for production sites.
