### ISSUE TITLE
Comments Conflict with Scroll to Top: Comment Links Anchor the User to the Top of Page

### ISSUE THREAD

**Issue by kartzke** [myApi/myApi#62]
When the Facebook comments plugin is set to use a Link... either Lightbox or Show / Hide... the user gets anchored to the top of the screen when they click the comments link.  This creates a strange user experience and will often scroll the comments box out of view, especially on Section and Category pages.

I believe this is because of the "Scroll to Top" functionality present in my template.  Many templates include a scroll to top feature using the hashtag as the anchor.  Is it possible to create a unique  #comments anchor? 

This would also be helpful if webmasters want to anchor people directly to the comments box on an article page.  We could even make a "Comments" button that looks similar to the Like / Send button.  That way, myApi could input a Like, Send, Share & Comment button to the top of the article. The comment button would simply anchor the person to the bottom of the article.

**Comment by thomaswelton** [comment]
Agreed. 
Also one thing I have noticed. Sometimes if the JS is taking a while to get ready a user can click on the Add a comment link and nothing will happen (as the JS isn't loaded yet) However the url will now contain the hash tag, I had plans to use the hash tag to detect that a user had tried to leave a comment. Once the JS is fully loaded it could read the tag and open the correct box.
