### ISSUE TITLE
Deploy comment box at K2 Items

### ISSUE THREAD

**Issue by motec-data** [myApi/myApi#65]
I can' deploy comment, share, like, send boxes at categories of K2.

For "Display on" select   "Show on selected article sections and categories (select below)", i can't see the K2 categories to select them.
That mens that all of my K2 Items (Blog and News) can't show comment box in case of "don't show comment on all articles.

Is there any way to deploy comment boxes to K2 content ONLY (see K2 categories at drop box)

Thanky
Harald

**Comment by motec-data** [comment]
Hi,
im sorry that nobody can help me. I spend two days to figure out how i can solve my problem...without success...

How can i deploy fabebook comment, like and share not to all articles BUT to some AND K2.
I can deploy to K2 articles only with "Deploy to ALL".... but of course at some articles i don't want to have them :-)

It whould be very, very nice to get some help

**Comment by papebih** [comment]
you can show comments on k2 if you set on my api show on all article, Very importet for me was that i removed social button code from k2 component. Social button for me was Facebook share button. I hope i help you
