### ISSUE TITLE
Fatal Error - URL file-access is disabled

### ISSUE THREAD

**Issue by tavoplus** [myApi/myApi#66]
Gustavo Da Silva 17 de junio a las 9:05
I´m user of myApi long tima ago, it's an amazing tool.
I upgraded myApi from 1.2 to 1.3.4 and when i try to reach the components from the menu sent this error: "Fatal error: Class 'JModelAdmin' not found in /public_html/cms/administrator/components/com_myapi/models/plugin.php on line 36.
It Happens when i trying to get this options from the component menu:
- App Settings
- Tab Applications
- Open Graph
- Comments
- Share
- Like
- Send

In other hand, when i go to "Real time" option, it send me this error

Warning: file_get_contents() [function.file-get-contents]: URL file-access is disabled in the server configuration in /home/veredan/public_html/cms/administrator/components/com_myapi/models/realtime.php on line 45

Warning: file_get_contents(https://graph.facebook.com/oauth/access_token?client_id=xxxxxxxx&client_secret=xxxxxxxxxxxxxxxxx&grant_type=client_credentials) [function.file-get-contents]: failed to open stream: no suitable wrapper could be found in /public_html/cms/administrator/components/com_myapi/models/realtime.php on line 45

i uninstalled every component an plugins, and started fro 0, but the error persist.
Thanks a lot!!

**Comment by bodytalk** [comment]
I have the same issue !

**Comment by thomaswelton** [comment]
Ok, you guys can contact your hosting provider, tell them you get this error
 URL file-access is disabled in the server configuration
See if they can change to configuration, I'll also work on a alternate method so anyone who has this disabled can use myApi with no issues.

**Comment by thomaswelton** [comment]
For now it may be best to contact your hosting provider, file_get_contents is the example code Facebook use here, http://developers.facebook.com/docs/authentication/

I'll still look into making this easier in a future version and will leave this defect open

**Comment by tavoplus** [comment]
Thank you my fried!

Gustavo Da Silva

-----Mensaje original-----
De: thomaswelton [mailto:reply@reply.github.com] 
Enviado el: miércoles, 22 de junio de 2011 05:43 a.m.
Para: gds@veredanet.com
Asunto: Re: [myApi] Fatal error, i tryed everything (#66)

For now it may be best to contact your hosting provider, file_get_contents is the example code Facebook use here, http://developers.facebook.com/docs/authentication/

I'll still look into making this easier in a future version and will leave this defect open

##

**Comment by tavoplus** [comment]
Hi tom.

I contacted my host service. 

I asked this:

I installed an myApi 1.3.4 Library in my Joomla website, and it present an issue. I contacted the developer, and told me this:

For now it may be best to contact your hosting provider, file_get_contents is the example code Facebook use here, http://developers.facebook.com/docs/authentication/

Can you hel me, or give me some directions to solve the issue.

Thanks
Gustavo

And they anwered the follow:

Hello Gustavo,

Thank you for your patience.

Please note that file_get_contents is not a PHP module but is coding based. We do not assist with coding or content issues in these regards for which we apologize however you must contact a web developer for further assistance in these regards. If you find that there are any server side modifications required we will be happy to assist you further.

Can you tell me or give some directions to solve the issue

Thanks a lot
GDS

**Comment by thomaswelton** [comment]
contact your hosting provider, tell them you get this error
"URL file-access is disabled in the server configuration"

**Comment by tavoplus** [comment]
Hi Tom.

the responso of the helpdesk of my hosting is:

# 1st mail:

Hello Gustavo,

I have replaced the php.ini file in public_html with a copy of the server's global php.ini.  I have copied the settings you have defined over to this file, so now allow_url_fopen is correctly set to enabled.

If you are still receiving this error, please provide us with the exact steps to replicate the issue, as well as any login information we will need to get there, and we will be happy to investigate further.

Regards,

2nd mail:
Hello Gustavo,

Thank you for your response. The error that you have provided is directly affiliated with your CMS and coding:

Fatal error: Class 'JModelAdmin' not found in /home/veredan/public_html/cms/administrator/components/com_myapi/models/plugin.php on line 36

You must contact a developer for assistance as unfortunately we do not assist with coding or content related issues.

Thank you. 

PLs Tom can you tell me the correct parameter in the php.ini ? I´m in the dark!

**Comment by thomaswelton** [comment]
Looking at their response things seem like that should be fine. Please try again and post any errors you get

**Comment by tavoplus** [comment]
I tryed and the issue persist

**Comment by thomaswelton** [comment]
The JModelAdmin defect is begins cause as you are using the dev build of myApi, I'd recommend you stick the the stable builds in the future.
Install this for now https://github.com/thomaswelton/myApi/zipball/master

**Comment by tavoplus** [comment]
It's working now!!

**Comment by thomaswelton** [comment]
Is everything ok for you @bodytalk ? If so I'd like to close this defect,
Also @tavoplus if you everything is working for you and you find myApi useful please review it here 
http://extensions.joomla.org/extensions/social-web/facebook-display/11624

**Comment by tavoplus** [comment]
Hi Thomas.

It works now in most menu options, but, in the real time, still have an issue, and my web page doesnt connect with facebook like 1.2 version did, all the facebook boxes its in blank.

Warning: file_get_contents() [function.file-get-contents]: URL file-access is disabled in the server configuration in /home/veredan/public_html/cms/administrator/components/com_myapi/models/realtime.php on line 45

Warning: file_get_contents(https://graph.facebook.com/oauth/access_token?client_id=145923672087407&client_secret=76dfcdc91c374e38e71a9535a9e20501&grant_type=client_credentials) [function.file-get-contents]: failed to open stream: no suitable wrapper could be found in /home/veredan/public_html/cms/administrator/components/com_myapi/models/realtime.php on line 45

Fatal error: Uncaught OAuthException: (#15) The method you are calling must be called with an app secret signed session thrown in /home/veredan/public_html/cms/plugins/system/myApiConnectFacebook.php on line 563

I know tha myApi it's a wonderfull free library, but if we have an install doc, it wil be better. Thanks a lot for your help

**Comment by thomaswelton** [comment]
Ok, so looks like there may still be an issue with your server configuration. It says "URL file-access is disabled in the server configuration"

Your web hosts said they changed the config and it should be ok, but looks like "URL file-access is disabled in the server configuration" so copy paste that message to your hosting provider. Also in their last email to you they asked for you to send them steps to replicate if there was still a problem so you may need to give them more info.

**Comment by tavoplus** [comment]
Hi Tom

Ready. It works, but aparently does'nt connect with my application in Facebook. (It worked in the past with 1.2 version)

In my Fb Page tab appears this issue

La aplicación no está disponible temporalmente
Errores de tipo Parse:

FBML Error (line 6): illegal tag "base" under "fb:tab-position"

FBML Error (line 65): illegal tag "body" under "fb:tab-position"

FBML Error (line 115): illegal event "onlogin" in tag "fb:custom-tag"

CSS Error (line 577 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 580 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 581 char 12): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 582 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 585 char 12): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 590 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 591 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 593 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 594 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 596 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 598 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 600 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 603 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 615 char 13): Expected color.  Error in parsing value for property.: 'color'  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 620 char 16): Expected ":".  Declaration dropped.

CSS Error (line 804 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 829 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 850 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 872 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 893 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 914 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 934 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 954 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 975 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 996 char 36): Error in parsing value for property.: 'text-align'  Declaration dropped.

CSS Error (line 1190 char 43): Error in parsing value for property.: 'outline-style'  Declaration dropped.

CSS Error (line 1190 char 67): Expected color.  Error in parsing value for property.: 'outline-color'  Declaration dropped.

CSS Error (line 1190 char 137): Error in parsing value for property.: 'background-image'  Declaration dropped.

CSS Error (line 1190 char 169): Error in parsing value for property.: 'background-attachment'  Declaration dropped.

CSS Error (line 1190 char 189): Unknown property.: 'background-origin'  Declaration dropped.

CSS Error (line 1190 char 215): Unknown property.: 'background-clip'  Declaration dropped.

CSS Error (line 1190 char 298): Error in parsing value for property.: 'background-position'  Declaration dropped.

CSS Error (line 1190 char 334): Error in parsing value for property.: 'background-repeat'  Declaration dropped.

CSS Error (line 1190 char 390): Expected color.  Expected color.  Expected end of value for property.  Error in parsing value for property.: 'border'  Declaration dropped.

Errores de tiempo de ejecución:

HTML error while rendering tag "link": There is a hard limit of 2 css link tags on profile tabs in order to remain under the IE 31 tag limit.

HTML error while rendering tag "link": There is a hard limit of 2 css link tags on profile tabs in order to remain under the IE 31 tag limit.

HTML error while rendering tag "link": There is a hard limit of 2 css link tags on profile tabs in order to remain under the IE 31 tag limit.

HTML error while rendering tag "link": There is a hard limit of 2 css link tags on profile tabs in order to remain under the IE 31 tag limit.

HTML error while rendering tag "link": There is a hard limit of 2 css link tags on profile tabs in order to remain under the IE 31 tag limit.

Cannot allow external script

**Comment by thomaswelton** [comment]
Go to your Facebook app setting, on Facebook.com Look for the settings for your tab application. Looks like you have FBML tabs enabled. Please change it to use iframe apps instead.

**Comment by tavoplus** [comment]
Hi again.

Apparently it works, but doesn't show nothing in any myApi Box. I know i'm very close

you will see in http://www.veredanet.com/cms/

**Comment by tavoplus** [comment]
Hi 

I was testing myApi, it works now, but has som problems with most of templates do i have. Can you tell me the parameters on the ccs file for the library.

**Comment by tavoplus** [comment]
Hi Thomas

I don't know if thi issue happens only me. myApi works now, but, the login box with fb avatars, the activity boxes only works in Firefox and with few templates. I test about 20, and only worked with JA_Purity, rhuk_milkyway. I install the last version 1.3.4.1 and have the same problem.

thanks for your help

**Comment by ashraf541** [comment]
//to test such functions you need do the following
$w = stream_get_wrappers();
echo 'openssl: ',  extension_loaded  ('openssl') ? 'yes':'no', "\n";
echo '<br/>';
echo 'http wrapper: ', in_array('http', $w) ? 'yes':'no', "\n";
echo '<br/>';
echo 'https wrapper: ', in_array('https', $w) ? 'yes':'no', "\n";
echo '<br/>';
echo 'wrappers: ', var_dump($w);

//after that i figured out that i need to use this function 
function get_myurl_data($url) {
    $ch = curl_init();
    $timeout = 5;
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
    $data = curl_exec($ch);
    curl_close($ch);
    return $data;
}
//instead of file_get_contents and it worked just fine !
