### ISSUE TITLE
Error Notice: Undefined property: stdClass::$id in plugins\content\myApiComment.php on line 44

### ISSUE THREAD

**Issue by chintancm** [myApi/myApi#7]
Hi,
I am constantly getting following error when my error reporting is set to maximum.

Notice: Undefined property: stdClass::$id in D:\Hosting\5949872\html\plugins\content\myApiComment.php on line 44

Notice: Undefined property: stdClass::$id in D:\Hosting\5949872\html\plugins\content\myApiShare.php on line 47

Notice: Undefined property: stdClass::$id in D:\Hosting\5949872\html\plugins\content\myApiLike.php on line 47

and this error even got indexed with google also and come as google SERP when searched for these error my website is getting listed and it exposes the path of my hosting account.

My website: www.BeyondToyz.in

Temporarily I've set error reporting to simple.

Regards,
Chintan

**Comment by thomaswelton** [comment]
Let me know if the latest version fixes this for you.

**Comment by chintancm** [comment]
It didnt fix my problem...
I am getting following error now

This webpage is not available
The server at www.facebook.com can't be found, because the DNS lookup failed. DNS is the web service that translates a website's name to its internet address. This error is most often caused by having no connection to the internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing Google Chrome from accessing the network.
Here are some suggestions:
Reload this web page later.
Check your internet connection. Reboot any routers, modems, or other network devices you may be using.
Check your DNS settings. Contact your network administrator if you're not sure what this means.
Try disabling DNS prefetching by following these steps: Go to Wrench menu > Options > Under the Hood and deselect "Use DNS pre-fetching to improve page load performance."
Try adding Google Chrome as a permitted program in your firewall or antivirus software's settings. If it is already a permitted program, try deleting it from the list of permitted programs and adding it again.
If you use a proxy server, check your proxy settings or check with your network administrator to make sure the proxy server is working.
If you don't believe you should be using a proxy server, try the following steps: Go to Wrench menu > Options > Under the Hood > Change proxy settings > LAN Settings and deselect "Use a proxy server for your LAN."
Error 105 (net::ERR_NAME_NOT_RESOLVED): Unable to resolve the server's DNS address.

**Comment by thomaswelton** [comment]
You still getting this issue? What are the latest errors in the php logs?

**Comment by chintancm** [comment]
Yes.The issue got resolved now.
Thanks for the update.

**Comment by thomaswelton** [comment]
Great, if myApi is all working and you find it useful and would like to support the project you can leave a short review here, many thanks 
http://extensions.joomla.org/extensions/social-web/facebook-display/11624
