### ISSUE TITLE
Newbie needs some help - go easy on me :-)

### ISSUE THREAD

**Issue by JaymeeGirly** [myApi/myApi#70]
Hi,

I am trying to install the Facebook Api and keep getting a fatal error that looks like this:

Fatal error: Cannot access protected property JInstaller::$_overwrite in /home/#/public_html/administrator/components/com_myapi/install.myapi.php on line 52

I am VERY new to all this and am very frustrated. I was able to upload and install a previous extension/plugin with Joomla's install manager, but for what ever reason I can't figure this one out.

Please someone help me, I'm ready to rip my hair out.

Do I upload as a zipped folder or do I upload after extracting first? What about the "Super Installer" where can i find this?

**Comment by JaymeeGirly** [comment]
Okay, nevermind. I am using Joomla 1.6 and I installed 1.5 just to test and it worked fine. When will this work for 1.6? I can't wait :-)

**Comment by thomaswelton** [comment]
You are using joomla 1.6.
myApi is not compatible with joomla 1.6.
There is a dev version that works on 1.6 but it's not public yet.
