### ISSUE TITLE
website slowing down?

### ISSUE THREAD

**Issue by josh1** [myApi/myApi#71]
Hi, when i enable the plugins my website seems to slow down? is this normal?
i also tried using the like button but it didnt seem to register my vote? maybe i have missed something in the settings?
it seems to be linked to my FB acc ok now. i was getting a "token" error and first but double checked the app code and auth code and it seems to get rid of the problem

Cheers Josh

**Comment by thomaswelton** [comment]
Hey, spoke to you on FB, did a test with myApi enabled and disabled. The site actually loaded faster with myApi enabled in my test, just an example that load time for site hosted on shared servers can fluctuate a lot. But it appears like myApi did not slow you down.
Closing the defect.
