### ISSUE TITLE
Important Feature Request - Synchronize User

### ISSUE THREAD

**Issue by abed-fatafta** [myApi/myApi#72]
When  i have lets say 40 User connected with my application , thin my database dropped by mistake , and there is no back up , i must be able to synchronize all connected users with joomla users , auto register them again , or if they registered again to  synchronize account linking if  they allow my application

**Comment by thomaswelton** [comment]
Right now the only way I can recommend you protect yourself from databases dropping by mistake is to make backups. Cleaning up the issue tracker, closing this.
