### ISSUE TITLE
Like box issue

### ISSUE THREAD

**Issue by patience-zz** [myApi/myApi#73]
When people press the like button from the website, they are not linked to the Fan page.  people who are linked to the fan page is if they login from Facebook itself and go to the page and press the like button.

**Comment by thomaswelton** [comment]
The like button added to articles is not designed to have this functionality instead it "likes" the article or web page. You most likely want the myapi fan box module and in the module parameters specify the Facebook page you want to like. 

If this resolves the issue please close the topic, if not let me know

**Comment by patience-zz** [comment]
yeah sorry the fanbox. I have set the parameters to the app page.

**Comment by thomaswelton** [comment]
so can this be closed?
