### ISSUE TITLE
email notification stopped working. 

### ISSUE THREAD

**Issue by patience-zz** [myApi/myApi#74]
I used to receive email notifications when people commented on my website, It worked for a while and now it has stopped completely.  the option is on from the backend and everything.

**Comment by thomaswelton** [comment]
Are your other non myApi emails still going through? Can I get the link for your site again.

**Comment by patience-zz** [comment]
yeah, the other extensions work.

**Comment by papebih** [comment]
today i see that do not recive email notifications when somment is posted. Before it worked ok
