### ISSUE TITLE
Error during install on joomla 1.7

### ISSUE THREAD

**Issue by MusiKreAktiv** [myApi/myApi#79]
HI!
I got the following message and don't know how to deal with it. Any options?
Fatal error: Cannot access protected property JInstaller::$_overwrite in /homepages/32/d277056760/htdocs/Wooge2011/administrator/components/com_myapi/install.myapi.php on line 48

Thanks for your help!
Jens

**Comment by thomaswelton** [comment]
it's not fully supported on 1.6 on some versions it doesn't work and produces this error.

**Comment by dantien** [comment]
Also tested it out with 1.7... but i got this error after enabeling the myApiConnect: HTTP Error 500 (Internal Server Error): An unexpected condition was encountered while the server was attempting to fulfil the request.

**Comment by thomaswelton** [comment]
It's not officially 1.7 compatible, however for me installing the  
master branch of myApi works on 1.7, version 1.3.4 does not work on 1.7
