### ISSUE TITLE
Issue with registration email after connecting 

### ISSUE THREAD

**Issue by edcarpenter3** [myApi/myApi#80]
When users register on the site using the Connect with Facebook button, although a user account is created and all details are added to the admin side of the site.

However, in the admin and user email, their name is not included in the email subject line, it just states "Account details for". The username and name is included in the body of the email, but not the subject line

**Comment by vivekratnavel** [comment]
I had the same issue and I made the following changes to correct it.
Open the file components/com_myapi/controller.php
Replace Line 589 with
        $subject    = sprintf ( JText::_( 'Account details for %s at %s' ), $name, $sitename);
Replace Line 625 with
        $subject2 = sprintf ( JText::_( 'Account details for %s at %s' ), $name, $sitename);

**Comment by vivekratnavel** [comment]
I found out the exact solution.
The below line is missing in "language/en-GB/en-GB.com_myapi.ini"

ACCOUNT DETAILS FOR=Account Details for %s at %s
