### ISSUE TITLE
website crashed with "100 Facebook needs the JSON PHP extension" 

### ISSUE THREAD

**Issue by wuffy26** [myApi/myApi#82]
Urgent! Thank you for reading this...

After i installed myApi 1.3.4.2 into Joomla 1.5 system, webpage changed from control panel to "Error. 100 Facebook needs the JSON PHP extension". 

Main website www.positive2u.com (a Chinese based web), together with administrator failed to get accessed. 

What should i do next? Uninstall it? (But How to uninstall the component since i failed to locate the administrator site)

Your help is much appreciated. Thanks!

**Comment by thomaswelton** [comment]
Contact your hosting provider and ask them to install the "JSON php extension" if they can not do this you will have to uninstall myApi, you can do this by turning off the myApi plugins in your database
