### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by vakil123** [myApi/myApi#83]
Fatal error: require_once() [function.require]: Failed opening required '/home/content/***_/plugins/system/myApiDom.php' (include_path='.:/usr/local/php5/lib/php') in /home/content/**_*/plugins/content/myApiOpenGraphContent.php on line 57

I get the above error when I try to save articles please can anyone tell me why this is so. Is it because I had installed this plugin myapi and then uninstalled it.

How to resolve this issue.

Thank you.

**Comment by Hiflo** [comment]
Hi,

I get a similar error when trying to uninstall:

Warning: require_once(/home/pro22416/public_html/administrator/components/com_myapi/helpers/facebook.php) [function.require-once]: failed to open stream: No such file or directory in /home/pro22416/public_html/plugins/system/myApiConnect.php on line 56

Fatal error: require_once() [function.require]: Failed opening required '/home/pro22416/public_html/administrator/components/com_myapi/helpers/facebook.php' (include_path='.:/usr/local/share/pear:/usr/lib/php:/usr/local/lib/php') in /home/pro22416/public_html/plugins/system/myApiConnect.php on line 56

Joomla V1.5.17
myApi V1.1.6

In the process of removing extensions before upgrading from Joomla V1.5 to V2.5

I get the above error on front-end after removing plug-in, have install file again to fix.

I tried removing the myApi php & xml files from my home directory first, front-end loaded OK, removed plug-in then Fatal Error again.

Are there some detailed instructions how to uninstall please, I'm presuming when I uninstall there is still some myApi data in mySQL causing the problem however I don't know SQL.

Thank You
