### ISSUE TITLE
 Fatal error: Uncaught exception 'Exception' with message 'Facebook needs the CURL PHP extension

### ISSUE THREAD

**Issue by shivpintu** [myApi/myApi#87]
Hi Team,

I have installed myAPI but i am getting below error while entering my Cereadt id and APP id in myAPI Setting tab. Please suggest what to do?

Fatal error: Uncaught exception 'Exception' with message 'Facebook needs the CURL PHP extension.' in C:\xampp\htdocs\new_vgyan\plugins\system\myApiConnectFacebook.php:20 Stack trace: #0 C:\xampp\htdocs\new_vgyan\administrator\components\com_myapi\controller.php(189): require_once() #1 C:\xampp\htdocs\new_vgyan\administrator\components\com_myapi\controller.php(163): MyapiController->save_myApiConnect() #2 C:\xampp\htdocs\new_vgyan\libraries\joomla\application\component\controller.php(236): MyapiController->savePlugin() #3 C:\xampp\htdocs\new_vgyan\administrator\components\com_myapi\myapi.php(27): JController->execute('savePlugin') #4 C:\xampp\htdocs\new_vgyan\libraries\joomla\application\component\helper.php(162): require_once('C:\xampp\htdocs...') #5 C:\xampp\htdocs\new_vgyan\administrator\includes\application.php(136): JComponentHelper->renderComponent('com_myapi') #6 C:\xampp\htdocs\new_vgyan\administrator\index.php(67): JAdministrator->dispatch('com_myapi') #7 {main} thrown in C:\xampp\htdocs\new_vgyan\plugins\system\myApiConnectFacebook.php on line 20

**Comment by pR0Ps** [comment]
You need the cURL extension of PHP to use the extension. See http://www.php.net/manual/en/curl.installation.php for installation help.
